### ISSUE TITLE
Bonjour, je trouve ou mon nom d'utilisateur et mon mot de passe pronote ? merci.

### ISSUE THREAD

**Issue by snowdqdzq** [pronote-notifications/pronote-notifications-app#1]

**Comment by snowdqdzq** [comment]
Ah c'est bon enfaite désolé :/

**Comment by Mistera91** [comment]
Je ne le trouve pas non plus (à part un truc dans les données de l'application pronote mais il ne marche pas :() Sous quelle forme sont les identifiants ? Il y a t-il une e-mail où juste initialeNomDeFamille par ce que c'est tout ce que je trouve avec un mot de passe assez long en caps lock et hexadécimal.

**Comment by Mistera91** [comment]
(ça aurait été bien de montrer ta solution si tu en as trouvé une)

**Comment by ghost** [comment]
Juste pour dire que je suis dans le même cas. Merci de votre aide
