### ISSUE TITLE
Suggestion : Open the real Pronote application when you click on a notification

### ISSUE THREAD

**Issue by SimonLeclere** [pronote-notifications/pronote-notifications-app#3]
It would be convenient to be able to click on a notification to instantly access the Pronote application, instead of accessing the Pronote-notifications settings :)

ThAnKs SiMoN 🤪

**Comment by Androz2091** [comment]
@SimonLeclere ça pourrait être une bonne idée, après ça pourrait être encore mieux de rediriger les utilisateurs vers la page "Historique des notifications" parce que le temps de chargement pour ouvrir Pronote Notifications est beaucoup plus rapide que celui pour ouvrir Pronote (et toutes les infos sont déjà dans l'historique de Pronote Notifications)

**Comment by SimonLeclere** [comment]
Ca marche aussi :)
