### ISSUE TITLE
Suggestion: Better login interface

### ISSUE THREAD

**Issue by SimonLeclere** [pronote-notifications/pronote-notifications-app#4]
Getting the URL of Pronote can be complicated for some people.
Instead, it might be interesting to add a checkbox to determine whether or not the user is using an ent, and to display a drop-down menu with the list of ent/lycees accordingly.

I don't know if this is difficult to do or not but it would greatly improve the intuitiveness of your application.

**Comment by Androz2091** [comment]
Salut,
C'est actuellement impossible, la liste des lycées n'est pas publique et le seul moyen d'identifier un lycée est d'avoir son URL (et la liste des ces URLs n'est pas publique non plus...)
