### ISSUE TITLE
Notifs pour des anciennes notes

### ISSUE THREAD

**Issue by SimonLeclere** [pronote-notifications/pronote-notifications-app#5]
Bonjour, ce matin j'ai eu une notification pour une note datant d'il y a trois mois.

Je ne sais pas exactement d'où viens l'erreur mais ça pourrait être gênant pour certains utilisateurs.

N'hésite pas à me demander plus de précisions si besoin :)

**Comment by Androz2091** [comment]
Je pense que c'est réglé et que ce genre de problèmes n'arrive plus
